FROM node:22-alpine
WORKDIR /app/backend
COPY backend/package.json backend/package-lock.json* ./
RUN npm ci
COPY backend/drizzle.config.ts ./
COPY database/migrations ../database/migrations
COPY backend/src/db/schema src/db/schema/
CMD ["npx", "drizzle-kit", "migrate", "--config=drizzle.config.ts"]
